import { CityEntry } from "./types";

export const AVAILABLE_CITIES: CityEntry[] = [
  // ─── Americas ────────────────────────────────────────────────────────
  { timezone: "America/New_York", label: "New York", region: "Americas", utcOffset: "UTC-5", keywords: ["us", "usa", "eastern"] },
  { timezone: "America/New_York", label: "Washington DC", region: "Americas", utcOffset: "UTC-5", keywords: ["us", "usa", "dc"] },
  { timezone: "America/New_York", label: "Miami", region: "Americas", utcOffset: "UTC-5", keywords: ["us", "usa", "florida"] },
  { timezone: "America/New_York", label: "Atlanta", region: "Americas", utcOffset: "UTC-5", keywords: ["us", "usa", "georgia"] },
  { timezone: "America/New_York", label: "Boston", region: "Americas", utcOffset: "UTC-5", keywords: ["us", "usa", "massachusetts"] },
  { timezone: "America/New_York", label: "Philadelphia", region: "Americas", utcOffset: "UTC-5", keywords: ["us", "usa"] },
  { timezone: "America/New_York", label: "Detroit", region: "Americas", utcOffset: "UTC-5", keywords: ["us", "usa", "michigan"] },
  { timezone: "America/Chicago", label: "Chicago", region: "Americas", utcOffset: "UTC-6", keywords: ["us", "usa", "central", "illinois"] },
  { timezone: "America/Chicago", label: "Houston", region: "Americas", utcOffset: "UTC-6", keywords: ["us", "usa", "texas"] },
  { timezone: "America/Chicago", label: "Dallas", region: "Americas", utcOffset: "UTC-6", keywords: ["us", "usa", "texas"] },
  { timezone: "America/Chicago", label: "Nashville", region: "Americas", utcOffset: "UTC-6", keywords: ["us", "usa", "tennessee"] },
  { timezone: "America/Chicago", label: "New Orleans", region: "Americas", utcOffset: "UTC-6", keywords: ["us", "usa", "louisiana"] },
  { timezone: "America/Denver", label: "Denver", region: "Americas", utcOffset: "UTC-7", keywords: ["us", "usa", "mountain", "colorado"] },
  { timezone: "America/Denver", label: "Salt Lake City", region: "Americas", utcOffset: "UTC-7", keywords: ["us", "usa", "utah"] },
  { timezone: "America/Phoenix", label: "Phoenix", region: "Americas", utcOffset: "UTC-7", keywords: ["us", "usa", "arizona"] },
  { timezone: "America/Los_Angeles", label: "Los Angeles", region: "Americas", utcOffset: "UTC-8", keywords: ["us", "usa", "california", "la", "western"] },
  { timezone: "America/Los_Angeles", label: "San Francisco", region: "Americas", utcOffset: "UTC-8", keywords: ["us", "usa", "california", "sf"] },
  { timezone: "America/Los_Angeles", label: "Seattle", region: "Americas", utcOffset: "UTC-8", keywords: ["us", "usa", "washington"] },
  { timezone: "America/Los_Angeles", label: "San Diego", region: "Americas", utcOffset: "UTC-8", keywords: ["us", "usa", "california"] },
  { timezone: "America/Los_Angeles", label: "Portland", region: "Americas", utcOffset: "UTC-8", keywords: ["us", "usa", "oregon"] },
  { timezone: "America/Los_Angeles", label: "Las Vegas", region: "Americas", utcOffset: "UTC-8", keywords: ["us", "usa", "nevada"] },
  { timezone: "America/Anchorage", label: "Anchorage", region: "Americas", utcOffset: "UTC-9", keywords: ["us", "usa", "alaska"] },
  { timezone: "Pacific/Honolulu", label: "Honolulu", region: "Americas", utcOffset: "UTC-10", keywords: ["us", "usa", "hawaii"] },
  { timezone: "America/Toronto", label: "Toronto", region: "Americas", utcOffset: "UTC-5", keywords: ["canada", "ontario"] },
  { timezone: "America/Toronto", label: "Montréal", region: "Americas", utcOffset: "UTC-5", keywords: ["canada", "quebec", "montreal"] },
  { timezone: "America/Toronto", label: "Ottawa", region: "Americas", utcOffset: "UTC-5", keywords: ["canada"] },
  { timezone: "America/Winnipeg", label: "Winnipeg", region: "Americas", utcOffset: "UTC-6", keywords: ["canada", "manitoba"] },
  { timezone: "America/Edmonton", label: "Edmonton", region: "Americas", utcOffset: "UTC-7", keywords: ["canada", "alberta"] },
  { timezone: "America/Edmonton", label: "Calgary", region: "Americas", utcOffset: "UTC-7", keywords: ["canada", "alberta"] },
  { timezone: "America/Vancouver", label: "Vancouver", region: "Americas", utcOffset: "UTC-8", keywords: ["canada", "british columbia"] },
  { timezone: "America/Halifax", label: "Halifax", region: "Americas", utcOffset: "UTC-4", keywords: ["canada", "nova scotia", "atlantic"] },
  { timezone: "America/St_Johns", label: "St. John's", region: "Americas", utcOffset: "UTC-3:30", keywords: ["canada", "newfoundland"] },
  { timezone: "America/Mexico_City", label: "Mexico City", region: "Americas", utcOffset: "UTC-6", keywords: ["mexico"] },
  { timezone: "America/Mexico_City", label: "Guadalajara", region: "Americas", utcOffset: "UTC-6", keywords: ["mexico"] },
  { timezone: "America/Cancun", label: "Cancún", region: "Americas", utcOffset: "UTC-5", keywords: ["mexico"] },
  { timezone: "America/Tijuana", label: "Tijuana", region: "Americas", utcOffset: "UTC-8", keywords: ["mexico"] },
  { timezone: "America/Guatemala", label: "Guatemala City", region: "Americas", utcOffset: "UTC-6", keywords: ["guatemala"] },
  { timezone: "America/Tegucigalpa", label: "Tegucigalpa", region: "Americas", utcOffset: "UTC-6", keywords: ["honduras"] },
  { timezone: "America/El_Salvador", label: "San Salvador", region: "Americas", utcOffset: "UTC-6", keywords: ["el salvador"] },
  { timezone: "America/Managua", label: "Managua", region: "Americas", utcOffset: "UTC-6", keywords: ["nicaragua"] },
  { timezone: "America/Costa_Rica", label: "San José", region: "Americas", utcOffset: "UTC-6", keywords: ["costa rica"] },
  { timezone: "America/Panama", label: "Panama City", region: "Americas", utcOffset: "UTC-5", keywords: ["panama"] },
  { timezone: "America/Havana", label: "Havana", region: "Americas", utcOffset: "UTC-5", keywords: ["cuba"] },
  { timezone: "America/Jamaica", label: "Kingston", region: "Americas", utcOffset: "UTC-5", keywords: ["jamaica"] },
  { timezone: "America/Port-au-Prince", label: "Port-au-Prince", region: "Americas", utcOffset: "UTC-5", keywords: ["haiti"] },
  { timezone: "America/Santo_Domingo", label: "Santo Domingo", region: "Americas", utcOffset: "UTC-4", keywords: ["dominican republic"] },
  { timezone: "America/Puerto_Rico", label: "San Juan", region: "Americas", utcOffset: "UTC-4", keywords: ["puerto rico"] },
  { timezone: "America/Port_of_Spain", label: "Port of Spain", region: "Americas", utcOffset: "UTC-4", keywords: ["trinidad"] },
  { timezone: "America/Barbados", label: "Bridgetown", region: "Americas", utcOffset: "UTC-4", keywords: ["barbados"] },
  { timezone: "America/Bogota", label: "Bogota", region: "Americas", utcOffset: "UTC-5", keywords: ["colombia"] },
  { timezone: "America/Guayaquil", label: "Quito", region: "Americas", utcOffset: "UTC-5", keywords: ["ecuador"] },
  { timezone: "America/Guayaquil", label: "Guayaquil", region: "Americas", utcOffset: "UTC-5", keywords: ["ecuador"] },
  { timezone: "America/Lima", label: "Lima", region: "Americas", utcOffset: "UTC-5", keywords: ["peru"] },
  { timezone: "America/La_Paz", label: "La Paz", region: "Americas", utcOffset: "UTC-4", keywords: ["bolivia"] },
  { timezone: "America/Caracas", label: "Caracas", region: "Americas", utcOffset: "UTC-4", keywords: ["venezuela"] },
  { timezone: "America/Guyana", label: "Georgetown", region: "Americas", utcOffset: "UTC-4", keywords: ["guyana"] },
  { timezone: "America/Paramaribo", label: "Paramaribo", region: "Americas", utcOffset: "UTC-3", keywords: ["suriname"] },
  { timezone: "America/Cayenne", label: "Cayenne", region: "Americas", utcOffset: "UTC-3", keywords: ["french guiana"] },
  { timezone: "America/Argentina/Buenos_Aires", label: "Buenos Aires", region: "Americas", utcOffset: "UTC-3", keywords: ["argentina"] },
  { timezone: "America/Argentina/Cordoba", label: "Córdoba", region: "Americas", utcOffset: "UTC-3", keywords: ["argentina"] },
  { timezone: "America/Santiago", label: "Santiago", region: "Americas", utcOffset: "UTC-3", keywords: ["chile"] },
  { timezone: "America/Punta_Arenas", label: "Punta Arenas", region: "Americas", utcOffset: "UTC-3", keywords: ["chile"] },
  { timezone: "America/Asuncion", label: "Asunción", region: "Americas", utcOffset: "UTC-4", keywords: ["paraguay"] },
  { timezone: "America/Montevideo", label: "Montevideo", region: "Americas", utcOffset: "UTC-3", keywords: ["uruguay"] },
  { timezone: "America/Sao_Paulo", label: "Rio de Janeiro", region: "Americas", utcOffset: "UTC-3", keywords: ["brazil", "brasil"] },
  { timezone: "America/Sao_Paulo", label: "Brasília", region: "Americas", utcOffset: "UTC-3", keywords: ["brazil", "brasil"] },
  { timezone: "America/Sao_Paulo", label: "Salvador", region: "Americas", utcOffset: "UTC-3", keywords: ["brazil", "brasil", "bahia"] },
  { timezone: "America/Recife", label: "Recife", region: "Americas", utcOffset: "UTC-3", keywords: ["brazil", "brasil"] },
  { timezone: "America/Fortaleza", label: "Fortaleza", region: "Americas", utcOffset: "UTC-3", keywords: ["brazil", "brasil"] },
  { timezone: "America/Belem", label: "Belém", region: "Americas", utcOffset: "UTC-3", keywords: ["brazil", "brasil"] },
  { timezone: "America/Manaus", label: "Manaus", region: "Americas", utcOffset: "UTC-4", keywords: ["brazil", "brasil", "amazonas"] },
  { timezone: "America/Cuiaba", label: "Cuiabá", region: "Americas", utcOffset: "UTC-4", keywords: ["brazil", "brasil"] },
  { timezone: "Atlantic/Stanley", label: "Stanley", region: "Americas", utcOffset: "UTC-3", keywords: ["falkland", "malvinas"] },

  // ─── Europe ──────────────────────────────────────────────────────────
  { timezone: "Europe/London", label: "London", region: "Europe", utcOffset: "UTC+0", keywords: ["uk", "england", "britain"] },
  { timezone: "Europe/London", label: "Edinburgh", region: "Europe", utcOffset: "UTC+0", keywords: ["uk", "scotland"] },
  { timezone: "Europe/London", label: "Cardiff", region: "Europe", utcOffset: "UTC+0", keywords: ["uk", "wales"] },
  { timezone: "Europe/London", label: "Belfast", region: "Europe", utcOffset: "UTC+0", keywords: ["uk", "northern ireland"] },
  { timezone: "Europe/Dublin", label: "Dublin", region: "Europe", utcOffset: "UTC+0", keywords: ["ireland"] },
  { timezone: "Atlantic/Reykjavik", label: "Reykjavik", region: "Europe", utcOffset: "UTC+0", keywords: ["iceland"] },
  { timezone: "Europe/Lisbon", label: "Lisbon", region: "Europe", utcOffset: "UTC+0", keywords: ["portugal"] },
  { timezone: "Atlantic/Azores", label: "Ponta Delgada", region: "Europe", utcOffset: "UTC-1", keywords: ["portugal", "azores"] },
  { timezone: "Europe/Paris", label: "Paris", region: "Europe", utcOffset: "UTC+1", keywords: ["france"] },
  { timezone: "Europe/Brussels", label: "Brussels", region: "Europe", utcOffset: "UTC+1", keywords: ["belgium"] },
  { timezone: "Europe/Amsterdam", label: "Amsterdam", region: "Europe", utcOffset: "UTC+1", keywords: ["netherlands", "holland"] },
  { timezone: "Europe/Luxembourg", label: "Luxembourg", region: "Europe", utcOffset: "UTC+1", keywords: [] },
  { timezone: "Europe/Berlin", label: "Berlin", region: "Europe", utcOffset: "UTC+1", keywords: ["germany", "deutschland"] },
  { timezone: "Europe/Berlin", label: "Frankfurt", region: "Europe", utcOffset: "UTC+1", keywords: ["germany", "deutschland"] },
  { timezone: "Europe/Berlin", label: "Munich", region: "Europe", utcOffset: "UTC+1", keywords: ["germany", "deutschland", "münchen"] },
  { timezone: "Europe/Zurich", label: "Zurich", region: "Europe", utcOffset: "UTC+1", keywords: ["switzerland", "zürich"] },
  { timezone: "Europe/Zurich", label: "Geneva", region: "Europe", utcOffset: "UTC+1", keywords: ["switzerland"] },
  { timezone: "Europe/Zurich", label: "Bern", region: "Europe", utcOffset: "UTC+1", keywords: ["switzerland"] },
  { timezone: "Europe/Vienna", label: "Vienna", region: "Europe", utcOffset: "UTC+1", keywords: ["austria", "wien"] },
  { timezone: "Europe/Madrid", label: "Madrid", region: "Europe", utcOffset: "UTC+1", keywords: ["spain", "espanha"] },
  { timezone: "Europe/Madrid", label: "Barcelona", region: "Europe", utcOffset: "UTC+1", keywords: ["spain", "espanha"] },
  { timezone: "Europe/Rome", label: "Rome", region: "Europe", utcOffset: "UTC+1", keywords: ["italy", "italia"] },
  { timezone: "Europe/Rome", label: "Milan", region: "Europe", utcOffset: "UTC+1", keywords: ["italy", "italia"] },
  { timezone: "Europe/Monaco", label: "Monaco", region: "Europe", utcOffset: "UTC+1", keywords: [] },
  { timezone: "Europe/Prague", label: "Prague", region: "Europe", utcOffset: "UTC+1", keywords: ["czech", "czechia"] },
  { timezone: "Europe/Budapest", label: "Budapest", region: "Europe", utcOffset: "UTC+1", keywords: ["hungary"] },
  { timezone: "Europe/Warsaw", label: "Warsaw", region: "Europe", utcOffset: "UTC+1", keywords: ["poland"] },
  { timezone: "Europe/Copenhagen", label: "Copenhagen", region: "Europe", utcOffset: "UTC+1", keywords: ["denmark"] },
  { timezone: "Europe/Stockholm", label: "Stockholm", region: "Europe", utcOffset: "UTC+1", keywords: ["sweden"] },
  { timezone: "Europe/Oslo", label: "Oslo", region: "Europe", utcOffset: "UTC+1", keywords: ["norway"] },
  { timezone: "Europe/Helsinki", label: "Helsinki", region: "Europe", utcOffset: "UTC+2", keywords: ["finland"] },
  { timezone: "Europe/Tallinn", label: "Tallinn", region: "Europe", utcOffset: "UTC+2", keywords: ["estonia"] },
  { timezone: "Europe/Riga", label: "Riga", region: "Europe", utcOffset: "UTC+2", keywords: ["latvia"] },
  { timezone: "Europe/Vilnius", label: "Vilnius", region: "Europe", utcOffset: "UTC+2", keywords: ["lithuania"] },
  { timezone: "Europe/Bucharest", label: "Bucharest", region: "Europe", utcOffset: "UTC+2", keywords: ["romania"] },
  { timezone: "Europe/Sofia", label: "Sofia", region: "Europe", utcOffset: "UTC+2", keywords: ["bulgaria"] },
  { timezone: "Europe/Athens", label: "Athens", region: "Europe", utcOffset: "UTC+2", keywords: ["greece"] },
  { timezone: "Europe/Kyiv", label: "Kyiv", region: "Europe", utcOffset: "UTC+2", keywords: ["ukraine", "kiev"] },
  { timezone: "Europe/Belgrade", label: "Belgrade", region: "Europe", utcOffset: "UTC+1", keywords: ["serbia"] },
  { timezone: "Europe/Zagreb", label: "Zagreb", region: "Europe", utcOffset: "UTC+1", keywords: ["croatia"] },
  { timezone: "Europe/Ljubljana", label: "Ljubljana", region: "Europe", utcOffset: "UTC+1", keywords: ["slovenia"] },
  { timezone: "Europe/Bratislava", label: "Bratislava", region: "Europe", utcOffset: "UTC+1", keywords: ["slovakia"] },
  { timezone: "Europe/Sarajevo", label: "Sarajevo", region: "Europe", utcOffset: "UTC+1", keywords: ["bosnia"] },
  { timezone: "Europe/Tirane", label: "Tirana", region: "Europe", utcOffset: "UTC+1", keywords: ["albania"] },
  { timezone: "Europe/Chisinau", label: "Chișinău", region: "Europe", utcOffset: "UTC+2", keywords: ["moldova"] },
  { timezone: "Europe/Malta", label: "Valletta", region: "Europe", utcOffset: "UTC+1", keywords: ["malta"] },
  { timezone: "Europe/Gibraltar", label: "Gibraltar", region: "Europe", utcOffset: "UTC+1", keywords: [] },
  { timezone: "Europe/Andorra", label: "Andorra", region: "Europe", utcOffset: "UTC+1", keywords: [] },
  { timezone: "Europe/Istanbul", label: "Istanbul", region: "Europe", utcOffset: "UTC+3", keywords: ["turkey", "türkiye"] },
  { timezone: "Europe/Istanbul", label: "Ankara", region: "Europe", utcOffset: "UTC+3", keywords: ["turkey", "türkiye"] },
  { timezone: "Europe/Minsk", label: "Minsk", region: "Europe", utcOffset: "UTC+3", keywords: ["belarus"] },
  { timezone: "Europe/Moscow", label: "Moscow", region: "Europe", utcOffset: "UTC+3", keywords: ["russia"] },
  { timezone: "Europe/Moscow", label: "St. Petersburg", region: "Europe", utcOffset: "UTC+3", keywords: ["russia", "saint petersburg"] },

  // ─── Africa ──────────────────────────────────────────────────────────
  { timezone: "Africa/Casablanca", label: "Casablanca", region: "Africa", utcOffset: "UTC+1", keywords: ["morocco"] },
  { timezone: "Africa/Casablanca", label: "Rabat", region: "Africa", utcOffset: "UTC+1", keywords: ["morocco"] },
  { timezone: "Africa/Tunis", label: "Tunis", region: "Africa", utcOffset: "UTC+1", keywords: ["tunisia"] },
  { timezone: "Africa/Algiers", label: "Algiers", region: "Africa", utcOffset: "UTC+1", keywords: ["algeria"] },
  { timezone: "Africa/Lagos", label: "Lagos", region: "Africa", utcOffset: "UTC+1", keywords: ["nigeria"] },
  { timezone: "Africa/Lagos", label: "Abuja", region: "Africa", utcOffset: "UTC+1", keywords: ["nigeria"] },
  { timezone: "Africa/Accra", label: "Accra", region: "Africa", utcOffset: "UTC+0", keywords: ["ghana"] },
  { timezone: "Africa/Dakar", label: "Dakar", region: "Africa", utcOffset: "UTC+0", keywords: ["senegal"] },
  { timezone: "Africa/Monrovia", label: "Monrovia", region: "Africa", utcOffset: "UTC+0", keywords: ["liberia"] },
  { timezone: "Africa/Cairo", label: "Cairo", region: "Africa", utcOffset: "UTC+2", keywords: ["egypt"] },
  { timezone: "Africa/Tripoli", label: "Tripoli", region: "Africa", utcOffset: "UTC+2", keywords: ["libya"] },
  { timezone: "Africa/Johannesburg", label: "Johannesburg", region: "Africa", utcOffset: "UTC+2", keywords: ["south africa"] },
  { timezone: "Africa/Johannesburg", label: "Cape Town", region: "Africa", utcOffset: "UTC+2", keywords: ["south africa"] },
  { timezone: "Africa/Johannesburg", label: "Pretoria", region: "Africa", utcOffset: "UTC+2", keywords: ["south africa"] },
  { timezone: "Africa/Khartoum", label: "Khartoum", region: "Africa", utcOffset: "UTC+2", keywords: ["sudan"] },
  { timezone: "Africa/Nairobi", label: "Nairobi", region: "Africa", utcOffset: "UTC+3", keywords: ["kenya"] },
  { timezone: "Africa/Addis_Ababa", label: "Addis Ababa", region: "Africa", utcOffset: "UTC+3", keywords: ["ethiopia"] },
  { timezone: "Africa/Dar_es_Salaam", label: "Dar es Salaam", region: "Africa", utcOffset: "UTC+3", keywords: ["tanzania"] },
  { timezone: "Africa/Kampala", label: "Kampala", region: "Africa", utcOffset: "UTC+3", keywords: ["uganda"] },
  { timezone: "Africa/Maputo", label: "Maputo", region: "Africa", utcOffset: "UTC+2", keywords: ["mozambique"] },
  { timezone: "Africa/Harare", label: "Harare", region: "Africa", utcOffset: "UTC+2", keywords: ["zimbabwe"] },
  { timezone: "Africa/Lusaka", label: "Lusaka", region: "Africa", utcOffset: "UTC+2", keywords: ["zambia"] },
  { timezone: "Africa/Luanda", label: "Luanda", region: "Africa", utcOffset: "UTC+1", keywords: ["angola"] },
  { timezone: "Africa/Kinshasa", label: "Kinshasa", region: "Africa", utcOffset: "UTC+1", keywords: ["congo", "drc"] },
  { timezone: "Africa/Windhoek", label: "Windhoek", region: "Africa", utcOffset: "UTC+2", keywords: ["namibia"] },

  // ─── Middle East ─────────────────────────────────────────────────────
  { timezone: "Asia/Jerusalem", label: "Jerusalem", region: "Middle East", utcOffset: "UTC+2", keywords: ["israel"] },
  { timezone: "Asia/Jerusalem", label: "Tel Aviv", region: "Middle East", utcOffset: "UTC+2", keywords: ["israel"] },
  { timezone: "Asia/Beirut", label: "Beirut", region: "Middle East", utcOffset: "UTC+2", keywords: ["lebanon"] },
  { timezone: "Asia/Damascus", label: "Damascus", region: "Middle East", utcOffset: "UTC+3", keywords: ["syria"] },
  { timezone: "Asia/Amman", label: "Amman", region: "Middle East", utcOffset: "UTC+3", keywords: ["jordan"] },
  { timezone: "Asia/Baghdad", label: "Baghdad", region: "Middle East", utcOffset: "UTC+3", keywords: ["iraq"] },
  { timezone: "Asia/Kuwait", label: "Kuwait City", region: "Middle East", utcOffset: "UTC+3", keywords: ["kuwait"] },
  { timezone: "Asia/Riyadh", label: "Riyadh", region: "Middle East", utcOffset: "UTC+3", keywords: ["saudi arabia"] },
  { timezone: "Asia/Riyadh", label: "Makkah", region: "Middle East", utcOffset: "UTC+3", keywords: ["saudi arabia", "mecca"] },
  { timezone: "Asia/Riyadh", label: "Medina", region: "Middle East", utcOffset: "UTC+3", keywords: ["saudi arabia"] },
  { timezone: "Asia/Qatar", label: "Doha", region: "Middle East", utcOffset: "UTC+3", keywords: ["qatar"] },
  { timezone: "Asia/Bahrain", label: "Manama", region: "Middle East", utcOffset: "UTC+3", keywords: ["bahrain"] },
  { timezone: "Asia/Dubai", label: "Dubai", region: "Middle East", utcOffset: "UTC+4", keywords: ["uae", "emirates"] },
  { timezone: "Asia/Dubai", label: "Abu Dhabi", region: "Middle East", utcOffset: "UTC+4", keywords: ["uae", "emirates"] },
  { timezone: "Asia/Muscat", label: "Muscat", region: "Middle East", utcOffset: "UTC+4", keywords: ["oman"] },
  { timezone: "Asia/Tehran", label: "Tehran", region: "Middle East", utcOffset: "UTC+3:30", keywords: ["iran"] },
  { timezone: "Asia/Tbilisi", label: "Tbilisi", region: "Middle East", utcOffset: "UTC+4", keywords: ["georgia"] },
  { timezone: "Asia/Yerevan", label: "Yerevan", region: "Middle East", utcOffset: "UTC+4", keywords: ["armenia"] },
  { timezone: "Asia/Baku", label: "Baku", region: "Middle East", utcOffset: "UTC+4", keywords: ["azerbaijan"] },
  { timezone: "Asia/Nicosia", label: "Nicosia", region: "Middle East", utcOffset: "UTC+2", keywords: ["cyprus"] },

  // ─── Asia ────────────────────────────────────────────────────────────
  { timezone: "Asia/Kabul", label: "Kabul", region: "Asia", utcOffset: "UTC+4:30", keywords: ["afghanistan"] },
  { timezone: "Asia/Karachi", label: "Karachi", region: "Asia", utcOffset: "UTC+5", keywords: ["pakistan"] },
  { timezone: "Asia/Karachi", label: "Lahore", region: "Asia", utcOffset: "UTC+5", keywords: ["pakistan"] },
  { timezone: "Asia/Karachi", label: "Islamabad", region: "Asia", utcOffset: "UTC+5", keywords: ["pakistan"] },
  { timezone: "Asia/Tashkent", label: "Tashkent", region: "Asia", utcOffset: "UTC+5", keywords: ["uzbekistan"] },
  { timezone: "Asia/Almaty", label: "Almaty", region: "Asia", utcOffset: "UTC+6", keywords: ["kazakhstan"] },
  { timezone: "Asia/Almaty", label: "Astana", region: "Asia", utcOffset: "UTC+6", keywords: ["kazakhstan"] },
  { timezone: "Asia/Kolkata", label: "Mumbai", region: "Asia", utcOffset: "UTC+5:30", keywords: ["india", "bombay"] },
  { timezone: "Asia/Kolkata", label: "Delhi", region: "Asia", utcOffset: "UTC+5:30", keywords: ["india", "new delhi"] },
  { timezone: "Asia/Kolkata", label: "Bangalore", region: "Asia", utcOffset: "UTC+5:30", keywords: ["india", "bengaluru"] },
  { timezone: "Asia/Kolkata", label: "Chennai", region: "Asia", utcOffset: "UTC+5:30", keywords: ["india", "madras"] },
  { timezone: "Asia/Kolkata", label: "Kolkata", region: "Asia", utcOffset: "UTC+5:30", keywords: ["india", "calcutta"] },
  { timezone: "Asia/Kolkata", label: "Hyderabad", region: "Asia", utcOffset: "UTC+5:30", keywords: ["india"] },
  { timezone: "Asia/Kolkata", label: "Pune", region: "Asia", utcOffset: "UTC+5:30", keywords: ["india"] },
  { timezone: "Asia/Colombo", label: "Colombo", region: "Asia", utcOffset: "UTC+5:30", keywords: ["sri lanka"] },
  { timezone: "Asia/Kathmandu", label: "Kathmandu", region: "Asia", utcOffset: "UTC+5:45", keywords: ["nepal"] },
  { timezone: "Asia/Dhaka", label: "Dhaka", region: "Asia", utcOffset: "UTC+6", keywords: ["bangladesh"] },
  { timezone: "Asia/Yangon", label: "Yangon", region: "Asia", utcOffset: "UTC+6:30", keywords: ["myanmar", "rangoon"] },
  { timezone: "Asia/Bangkok", label: "Bangkok", region: "Asia", utcOffset: "UTC+7", keywords: ["thailand"] },
  { timezone: "Asia/Bangkok", label: "Hanoi", region: "Asia", utcOffset: "UTC+7", keywords: ["vietnam"] },
  { timezone: "Asia/Ho_Chi_Minh", label: "Ho Chi Minh City", region: "Asia", utcOffset: "UTC+7", keywords: ["vietnam", "saigon"] },
  { timezone: "Asia/Jakarta", label: "Jakarta", region: "Asia", utcOffset: "UTC+7", keywords: ["indonesia"] },
  { timezone: "Asia/Phnom_Penh", label: "Phnom Penh", region: "Asia", utcOffset: "UTC+7", keywords: ["cambodia"] },
  { timezone: "Asia/Vientiane", label: "Vientiane", region: "Asia", utcOffset: "UTC+7", keywords: ["laos"] },
  { timezone: "Asia/Singapore", label: "Singapore", region: "Asia", utcOffset: "UTC+8", keywords: [] },
  { timezone: "Asia/Kuala_Lumpur", label: "Kuala Lumpur", region: "Asia", utcOffset: "UTC+8", keywords: ["malaysia"] },
  { timezone: "Asia/Shanghai", label: "Shanghai", region: "Asia", utcOffset: "UTC+8", keywords: ["china"] },
  { timezone: "Asia/Shanghai", label: "Beijing", region: "Asia", utcOffset: "UTC+8", keywords: ["china"] },
  { timezone: "Asia/Shanghai", label: "Shenzhen", region: "Asia", utcOffset: "UTC+8", keywords: ["china"] },
  { timezone: "Asia/Shanghai", label: "Chongqing", region: "Asia", utcOffset: "UTC+8", keywords: ["china"] },
  { timezone: "Asia/Hong_Kong", label: "Hong Kong", region: "Asia", utcOffset: "UTC+8", keywords: ["hk"] },
  { timezone: "Asia/Taipei", label: "Taipei", region: "Asia", utcOffset: "UTC+8", keywords: ["taiwan"] },
  { timezone: "Asia/Manila", label: "Manila", region: "Asia", utcOffset: "UTC+8", keywords: ["philippines"] },
  { timezone: "Asia/Makassar", label: "Denpasar", region: "Asia", utcOffset: "UTC+8", keywords: ["indonesia", "bali"] },
  { timezone: "Asia/Tokyo", label: "Tokyo", region: "Asia", utcOffset: "UTC+9", keywords: ["japan"] },
  { timezone: "Asia/Tokyo", label: "Osaka", region: "Asia", utcOffset: "UTC+9", keywords: ["japan"] },
  { timezone: "Asia/Seoul", label: "Seoul", region: "Asia", utcOffset: "UTC+9", keywords: ["south korea", "korea"] },
  { timezone: "Asia/Pyongyang", label: "Pyongyang", region: "Asia", utcOffset: "UTC+9", keywords: ["north korea"] },
  { timezone: "Asia/Vladivostok", label: "Vladivostok", region: "Asia", utcOffset: "UTC+10", keywords: ["russia"] },
  { timezone: "Asia/Kamchatka", label: "Petropavlovsk", region: "Asia", utcOffset: "UTC+12", keywords: ["russia", "kamchatka"] },

  // ─── Oceania ─────────────────────────────────────────────────────────
  { timezone: "Australia/Perth", label: "Perth", region: "Oceania", utcOffset: "UTC+8", keywords: ["australia", "western"] },
  { timezone: "Australia/Darwin", label: "Darwin", region: "Oceania", utcOffset: "UTC+9:30", keywords: ["australia", "northern territory"] },
  { timezone: "Australia/Adelaide", label: "Adelaide", region: "Oceania", utcOffset: "UTC+9:30", keywords: ["australia", "south"] },
  { timezone: "Australia/Brisbane", label: "Brisbane", region: "Oceania", utcOffset: "UTC+10", keywords: ["australia", "queensland"] },
  { timezone: "Australia/Sydney", label: "Sydney", region: "Oceania", utcOffset: "UTC+11", keywords: ["australia", "nsw"] },
  { timezone: "Australia/Sydney", label: "Canberra", region: "Oceania", utcOffset: "UTC+11", keywords: ["australia", "act"] },
  { timezone: "Australia/Melbourne", label: "Melbourne", region: "Oceania", utcOffset: "UTC+11", keywords: ["australia", "victoria"] },
  { timezone: "Australia/Hobart", label: "Hobart", region: "Oceania", utcOffset: "UTC+11", keywords: ["australia", "tasmania"] },
  { timezone: "Pacific/Auckland", label: "Auckland", region: "Oceania", utcOffset: "UTC+13", keywords: ["new zealand", "nz"] },
  { timezone: "Pacific/Auckland", label: "Wellington", region: "Oceania", utcOffset: "UTC+13", keywords: ["new zealand", "nz"] },
  { timezone: "Pacific/Fiji", label: "Suva", region: "Oceania", utcOffset: "UTC+12", keywords: ["fiji"] },
  { timezone: "Pacific/Port_Moresby", label: "Port Moresby", region: "Oceania", utcOffset: "UTC+10", keywords: ["papua new guinea"] },
  { timezone: "Pacific/Noumea", label: "Noumea", region: "Oceania", utcOffset: "UTC+11", keywords: ["new caledonia"] },
  { timezone: "Pacific/Apia", label: "Apia", region: "Oceania", utcOffset: "UTC+13", keywords: ["samoa"] },
  { timezone: "Pacific/Tongatapu", label: "Nuku'alofa", region: "Oceania", utcOffset: "UTC+13", keywords: ["tonga"] },
  { timezone: "Pacific/Tahiti", label: "Papeete", region: "Oceania", utcOffset: "UTC-10", keywords: ["french polynesia", "tahiti"] },
  { timezone: "Pacific/Guam", label: "Hagåtña", region: "Oceania", utcOffset: "UTC+10", keywords: ["guam"] },
];

const CITY_LABELS: Record<string, string> = {
  "America/Sao_Paulo": "São Paulo",
};
for (const city of AVAILABLE_CITIES) {
  if (!CITY_LABELS[city.timezone]) {
    CITY_LABELS[city.timezone] = city.label;
  }
}

export function getCityLabel(timezone: string): string {
  return CITY_LABELS[timezone] ?? timezone.split("/").pop()?.replace("_", " ") ?? timezone;
}
